planning_scene_monitor_options:
  name: "planning_scene_monitor"
  robot_description: "robot_description"
  joint_state_topic: "/joint_states"
  attached_collision_object_topic: "/attached_collision_object"
  publish_planning_scene_topic: "/planning_scene"
  monitored_planning_scene_topic: "/monitored_planning_scene"
  wait_for_initial_state_timeout: 10.0

planning_pipelines:
  pipeline_names: ["ompl", "isaac_ros_cumotion"]

isaac_ros_cumotion:
  planning_plugin: isaac_ros_cumotion_moveit/CumotionPlanner
  request_adapters: "default_planner_request_adapters/FixWorkspaceBounds, default_planner_request_adapters/FixStartStateBounds, default_planner_request_adapters/FixStartStateCollision, default_planner_request_adapters/FixStartStatePathConstraints"
  start_state_max_bounds_error: 0.1
  num_steps: 32

plan_request_params:
  planning_attempts: 1
  planning_pipeline: isaac_ros_cumotion
  planner_id: cuMotion
  max_velocity_scaling_factor: 1.0
  max_acceleration_scaling_factor: 1.0