controller_manager:
  ros__parameters:
    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster
    joint_trajectory_controller:
      type: joint_trajectory_controller/JointTrajectoryController
    robotiq_gripper_controller:
      type: position_controllers/GripperActionController
joint_trajectory_controller:
  ros__parameters:
    joints:
    - $(var tf_prefix)shoulder_pan_joint
    - $(var tf_prefix)shoulder_lift_joint
    - $(var tf_prefix)elbow_joint
    - $(var tf_prefix)wrist_1_joint
    - $(var tf_prefix)wrist_2_joint
    - $(var tf_prefix)wrist_3_joint
    command_interfaces:
    - position
    state_interfaces:
    - position
    - velocity
    state_publish_rate: 100.0
    action_monitor_rate: 20.0
    allow_partial_joints_goal: false
    constraints:
      stopped_velocity_tolerance: 0.2
      goal_time: 0.0
      $(var tf_prefix)shoulder_pan_joint:
        trajectory: 0.2
        goal: 0.1
      $(var tf_prefix)shoulder_lift_joint:
        trajectory: 0.2
        goal: 0.1
      $(var tf_prefix)elbow_joint:
        trajectory: 0.2
        goal: 0.1
      $(var tf_prefix)wrist_1_joint:
        trajectory: 0.2
        goal: 0.1
      $(var tf_prefix)wrist_2_joint:
        trajectory: 0.2
        goal: 0.1
      $(var tf_prefix)wrist_3_joint:
        trajectory: 0.2
        goal: 0.1
robotiq_gripper_controller:
  ros__parameters:
    joint: $(var tf_prefix)robotiq_85_left_knuckle_joint
    command_interface: position
    allow_stall: false
    goal_tolerance: 0.005
    stall_velocity_threshold: 0.01
    stall_timeout: 1.0
